[Kernel CI] Change some aur packages to official packages and Add missing ccache package in LTS build
Locietta/xanmod-kernel-WSL2 pull request #69
Opened 2024-07-19 07:41 UTC by Nevuly

Error Logs:
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 archlinuxcn downloading...
error: target not found: llvm-git
error: target not found: llvm-libs-git
error: target not found: clang-git
error: target not found: lld-git

 * llvm-git, llvm-libs-git, clang-git, lld-git is aur packages, It can't install with pacman.
 * They support at official packages, So change it.

2024-07-19 07:55 UTC, Nevuly commented
Today, I checked archlinuxcn, It removed in repo because they triggered to orphan packages.

https://github.com/archlinuxcn/repo/commit/960f21835fe2bc68638d44e100b4e018e9b060b0

2024-07-25 10:22 UTC, taalojarvi requested changes
LTS builds do not support ccache at the moment

2024-07-25 11:00 UTC, Nevuly commented on .github/workflows/build-lts.yml
> +        pacman -Syu --noconfirm pahole xmlto inetutils bc cpio jq llvm llvm-libs clang lld ccache
I'll update PR ASAP.

2024-07-25 11:44 UTC, Nevuly commented on .github/workflows/build-lts.yml
> +        pacman -Syu --noconfirm pahole xmlto inetutils bc cpio jq llvm llvm-libs clang lld ccache
Reverted.

2024-07-29 09:24 UTC, taalojarvi approved these changes

2024-08-02 00:45 UTC, Nevuly commented
I close this PR because It has been pending more than 2 weeks.

If this PR is necessary, please reopen.

Thanks.

2024-08-02 00:45 UTC, closed without merging